#this is a dataSpider
FROM scrapy:1.1

#image made by yuandong ni
MAINTAINER nyd "niyuandong@wis-eye.com"

#download the bot file
ADD slaveNode.tar /

#switch the workdir
WORKDIR /slaveNode

#run command
CMD ["scrapy","crawl","dataSpider"]




