version: '3.3'
services:
  urlspider:
    build: .
    # ports:
    #   - "27017:27017"
    volumes:
      - ./credentials:/root
    command: scrapy crawl urlSpider
  dataspider:
    build: .
    # ports:
    #   - "16379:6379"
    volumes:
      - ./credentials:/root
    command: scrapy crawl dataSpider
# volumes:
#   database:
