# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiderWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderTask',
            fields=[
                ('tid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cycletime', models.IntegerField()),
                ('url', models.URLField()),
                ('stra_delay', models.BooleanField()),
                ('stra_ua', models.BooleanField()),
                ('stra_proxy', models.BooleanField()),
                ('stra_js', models.BooleanField()),
                ('num_url', models.IntegerField()),
                ('num_data', models.IntegerField()),
                ('num_redis', models.IntegerField()),
                ('num_mongo', models.IntegerField()),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('editDate', models.DateTimeField(auto_now=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiderWeb.SpiderCase')),
            ],
        ),
    ]
