# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderWeb', '0003_auto_20170515_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spidertask',
            name='tid',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
