# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderWeb', '0005_spidertask_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderShell',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('tid', models.CharField(max_length=8)),
                ('text', models.TextField()),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
